apiVersion: v1
kind: Service
metadata:
  name: {{ template "onos-config.fullname" . }}
  labels:
    app: {{ template "onos-config.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    name: {{ template "onos-config.fullname" . }}
    app: onos
    type: config
    resource: {{ template "onos-config.fullname" . }}
  type: NodePort
  ports:
    - name: grpc
      port: 5150
