# Default values for onos-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: onosproject/onos-config
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

debug: false

namespace: default

devices: []

plugins: [devicesim.so.1.0.0,testdevice.so.1.0.0,testdevice.so.2.0.0,stratum.so.1.0.0]

store:
  enabled: false
  namespace: default
  raftgroup: raft
  controller: atomix-controller.default.svc.cluster.local:5679
  raft:
    partitions: 1
    partitionSize: 1

ingress:
  enabled: false

service:
  type: ClusterIP

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}