nameOverride: ""

replicas: 1
annotations: {}

image:
  repository: onosproject/onos-config
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

debug: false

devices: []

plugins: [devicesim.so.1.0.0,testdevice.so.1.0.0,testdevice.so.2.0.0,stratum.so.1.0.0]

store:
  enabled: false
  namespace: default
  raftgroup: raft
  controller: atomix-controller.default.svc.cluster.local:5679
  raft:
    partitions: 1
    partitionSize: 1

resources:
  requests:
    cpu: 0.5
    memory: 512Mi

ingress:
  enabled: false
